name: Test SSH Connection (Debug)

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug Network and Secrets
        run: |
          echo "--- DEBUGGING SSH CONNECTION ---"
          echo "Host Secret: ${{ secrets.HOST }}"
          echo "Username: www-data"
          echo "Port: 22"
          echo "Key First 20 chars: $(echo "${{ secrets.KEY }}" | head -c 20)"
          echo "Key Last 20 chars: $(echo "${{ secrets.KEY }}" | tail -c 20)"
          echo "Pinging..."
          ping -c 3 ${{ secrets.HOST }}
          echo "Connecting to port 22..."
          nc -zv ${{ secrets.HOST }} 22

      - name: Deploy to Alibaba Cloud (SSH)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: www-data
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            echo "Connected successfully!"
            pwd
            ls -la /var/www/
