name: Deploy to Alibaba Cloud

on:
  push:
    branches:
      - main  # Or your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Alibaba Cloud
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}      # Your server's IP
          username: www-data
          key: ${{ secrets.KEY }}       # The private key
          port: 22
          script: |
            cd /var/www/qingx.uk
            git pull origin main
            # If you have a build process, add it here:
            # npm run build
            # Or
            # hugo
            sudo systemctl reload nginx
