name: Test SSH Connection (Extreme Debug)

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug SSH Configuration
        run: |
          echo "--- DEBUGGING SSH CONFIGURATION ---"
          echo "Host Secret (Length): $(echo "${{ secrets.HOST }}" | wc -c)"
          echo "Host Secret Value: ${{ secrets.HOST }}"
          echo "Username: www-data"
          echo "Port: 22"
          echo "Key Secret (Length): $(echo "${{ secrets.KEY }}" | wc -c)"
          echo "Key First 20 chars: $(echo "${{ secrets.KEY }}" | head -c 20)"
          echo "Key Last 20 chars: $(echo "${{ secrets.KEY }}" | tail -c 20)"
          echo "--- END DEBUGGING ---"

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: www-data
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            echo "Connected to server!"
            pwd
            ls -la /var/www/
